name: Portfolio CI
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Setup Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v1.4.0
        with:
          channel: beta
      - run: flutter pub get

      # Format
      - name: Format
        run: flutter format --dry-run --set-exit-if-changed .

      # Build part files
      - name: Build part files
        run: flutter pub run easy_localization:generate -S assets/translations -O lib/presentation/generated

      # Analyze
      - name: Analyze
        run: flutter analyze
